### ISSUE TITLE
管理系コマンドの統合

### ISSUE THREAD

**Issue by hyouhyan** [Hyouhyan/Discord-Dorei#4]
~~打刻とかbus、idouで使えそう~~
Bot管理系コマンドを、`/control`に統合する。
controlを実行すると、いくつかのボタンが表示され、ボタンを押すことでbotを操作できる。

https://qiita.com/Broccolingual/items/b008421e535b96c05557

**Comment by Hyouhyan** [comment]
実装してみたいのは確かにそうだけど、具体的にどの機能・シーンで使おうか

**Comment by Hyouhyan** [comment]
Bot管理系コマンドを統合しよう。
send, shutdown, suteme, invite
これらを`/control`に統合し、コントロールパネル的な意味合いで、ボタンをクリックさせよう。
